# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 495)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 791, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.dirc_scan_tab1 = QtWidgets.QWidget()
        self.dirc_scan_tab1.setObjectName("dirc_scan_tab1")
        self.groupBox = QtWidgets.QGroupBox(self.dirc_scan_tab1)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 521, 61))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.url_lable = QtWidgets.QLabel(self.groupBox)
        self.url_lable.setGeometry(QtCore.QRect(10, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.url_lable.setFont(font)
        self.url_lable.setObjectName("url_lable")
        self.url_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.url_lineEdit.setGeometry(QtCore.QRect(40, 20, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(11)
        self.url_lineEdit.setFont(font)
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.start_scan_Button = QtWidgets.QPushButton(self.groupBox)
        self.start_scan_Button.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.start_scan_Button.setObjectName("start_scan_Button")
        self.stop_scan_Button = QtWidgets.QPushButton(self.groupBox)
        self.stop_scan_Button.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.stop_scan_Button.setObjectName("stop_scan_Button")
        self.groupBox_2 = QtWidgets.QGroupBox(self.dirc_scan_tab1)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 70, 521, 41))
        self.groupBox_2.setObjectName("groupBox_2")
        self.asp_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.asp_checkBox.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.asp_checkBox.setObjectName("asp_checkBox")
        self.php_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.php_checkBox.setGeometry(QtCore.QRect(60, 20, 71, 21))
        self.php_checkBox.setCheckable(True)
        self.php_checkBox.setChecked(False)
        self.php_checkBox.setObjectName("php_checkBox")
        self.sspx_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.sspx_checkBox.setGeometry(QtCore.QRect(110, 20, 71, 21))
        self.sspx_checkBox.setObjectName("sspx_checkBox")
        self.jsp_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.jsp_checkBox.setGeometry(QtCore.QRect(170, 20, 71, 21))
        self.jsp_checkBox.setObjectName("jsp_checkBox")
        self.jsp_checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.jsp_checkBox_2.setGeometry(QtCore.QRect(220, 20, 71, 21))
        self.jsp_checkBox_2.setObjectName("jsp_checkBox_2")
        self.jsp_checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.jsp_checkBox_3.setGeometry(QtCore.QRect(280, 20, 71, 21))
        self.jsp_checkBox_3.setObjectName("jsp_checkBox_3")
        self.jsp_checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.jsp_checkBox_4.setGeometry(QtCore.QRect(330, 20, 71, 21))
        self.jsp_checkBox_4.setObjectName("jsp_checkBox_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.dirc_scan_tab1)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 130, 521, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar.setGeometry(QtCore.QRect(10, 20, 501, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_4 = QtWidgets.QGroupBox(self.dirc_scan_tab1)
        self.groupBox_4.setGeometry(QtCore.QRect(530, 10, 241, 61))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(80, 10, 21, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(170, 10, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(80, 30, 21, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(170, 30, 21, 16))
        self.label_10.setObjectName("label_10")
        self.all_lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.all_lineEdit.setGeometry(QtCore.QRect(110, 0, 51, 20))
        self.all_lineEdit.setObjectName("all_lineEdit")
        self.finished_lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.finished_lineEdit.setGeometry(QtCore.QRect(110, 30, 51, 20))
        self.finished_lineEdit.setObjectName("finished_lineEdit")
        self.groupBox_5 = QtWidgets.QGroupBox(self.dirc_scan_tab1)
        self.groupBox_5.setGeometry(QtCore.QRect(530, 80, 241, 80))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.label_2.setObjectName("label_2")
        self.threads_lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.threads_lineEdit.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.threads_lineEdit.setObjectName("threads_lineEdit")
        self.reuslt_tableView = QtWidgets.QTableView(self.dirc_scan_tab1)
        self.reuslt_tableView.setGeometry(QtCore.QRect(10, 190, 761, 192))
        self.reuslt_tableView.setObjectName("reuslt_tableView")
        self.tabWidget.addTab(self.dirc_scan_tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.web_utl_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.web_utl_lineEdit.setGeometry(QtCore.QRect(90, 10, 251, 20))
        self.web_utl_lineEdit.setObjectName("web_utl_lineEdit")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.web_start_Button = QtWidgets.QPushButton(self.tab_2)
        self.web_start_Button.setGeometry(QtCore.QRect(370, 10, 75, 23))
        self.web_start_Button.setObjectName("web_start_Button")
        self.web_result_textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.web_result_textEdit.setGeometry(QtCore.QRect(10, 50, 431, 341))
        self.web_result_textEdit.setObjectName("web_result_textEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 341, 381))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.port_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.port_ip_lineEdit.setGeometry(QtCore.QRect(60, 20, 161, 31))
        self.port_ip_lineEdit.setObjectName("port_ip_lineEdit")
        self.source_ports_textEdit = QtWidgets.QTextEdit(self.groupBox_6)
        self.source_ports_textEdit.setGeometry(QtCore.QRect(0, 110, 331, 261))
        self.source_ports_textEdit.setObjectName("source_ports_textEdit")
        self.port_scan_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.port_scan_Button.setEnabled(False)
        self.port_scan_Button.setGeometry(QtCore.QRect(240, 20, 75, 23))
        self.port_scan_Button.setCheckable(False)
        self.port_scan_Button.setChecked(False)
        self.port_scan_Button.setObjectName("port_scan_Button")
        self.port_num_comboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.port_num_comboBox.setGeometry(QtCore.QRect(150, 70, 69, 22))
        self.port_num_comboBox.setModelColumn(0)
        self.port_num_comboBox.setObjectName("port_num_comboBox")
        self.port_num_comboBox.addItem("")
        self.port_num_comboBox.setItemText(0, "")
        self.port_num_comboBox.addItem("")
        self.port_num_comboBox.addItem("")
        self.port_num_comboBox.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 121, 21))
        self.label_8.setObjectName("label_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(370, 10, 401, 381))
        self.groupBox_7.setObjectName("groupBox_7")
        self.result_port_textEdit = QtWidgets.QTextEdit(self.groupBox_7)
        self.result_port_textEdit.setGeometry(QtCore.QRect(10, 20, 381, 341))
        self.result_port_textEdit.setObjectName("result_port_textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.domain_lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.domain_lineEdit.setGeometry(QtCore.QRect(100, 20, 141, 20))
        self.domain_lineEdit.setObjectName("domain_lineEdit")
        self.domain_start_Button = QtWidgets.QPushButton(self.tab_3)
        self.domain_start_Button.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.domain_start_Button.setObjectName("domain_start_Button")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 70, 241, 311))
        self.groupBox_8.setObjectName("groupBox_8")
        self.A_textEdit = QtWidgets.QTextEdit(self.groupBox_8)
        self.A_textEdit.setGeometry(QtCore.QRect(10, 20, 231, 281))
        self.A_textEdit.setObjectName("A_textEdit")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setGeometry(QtCore.QRect(270, 70, 221, 311))
        self.groupBox_9.setObjectName("groupBox_9")
        self.MX_textEdit = QtWidgets.QTextEdit(self.groupBox_9)
        self.MX_textEdit.setGeometry(QtCore.QRect(10, 20, 201, 281))
        self.MX_textEdit.setObjectName("MX_textEdit")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setGeometry(QtCore.QRect(510, 70, 261, 311))
        self.groupBox_10.setObjectName("groupBox_10")
        self.NS_textEdit = QtWidgets.QTextEdit(self.groupBox_10)
        self.NS_textEdit.setGeometry(QtCore.QRect(10, 20, 231, 281))
        self.NS_textEdit.setObjectName("NS_textEdit")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_7.setGeometry(QtCore.QRect(10, 10, 771, 381))
        self.textEdit_7.setObjectName("textEdit_7")
        self.tabWidget.addTab(self.tab_4, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 430, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.url_lable.setText(_translate("MainWindow", "URL:"))
        self.url_lineEdit.setText(_translate("MainWindow", "http://192.168.74.133"))
        self.start_scan_Button.setText(_translate("MainWindow", "开始扫描"))
        self.stop_scan_Button.setText(_translate("MainWindow", "停止扫描"))
        self.groupBox_2.setTitle(_translate("MainWindow", "网址程序"))
        self.asp_checkBox.setText(_translate("MainWindow", "ASP"))
        self.php_checkBox.setText(_translate("MainWindow", "PHP"))
        self.sspx_checkBox.setText(_translate("MainWindow", "ASPX"))
        self.jsp_checkBox.setText(_translate("MainWindow", "JSP"))
        self.jsp_checkBox_2.setText(_translate("MainWindow", "数据库"))
        self.jsp_checkBox_3.setText(_translate("MainWindow", "备份"))
        self.jsp_checkBox_4.setText(_translate("MainWindow", "高危"))
        self.groupBox_3.setTitle(_translate("MainWindow", "扫描状态"))
        self.label_3.setText(_translate("MainWindow", "扫描总数："))
        self.label_4.setText(_translate("MainWindow", "-----"))
        self.label_5.setText(_translate("MainWindow", "已扫描："))
        self.label_7.setText(_translate("MainWindow", "-----"))
        self.label_9.setText(_translate("MainWindow", "-----"))
        self.label_10.setText(_translate("MainWindow", "-----"))
        self.all_lineEdit.setText(_translate("MainWindow", "0"))
        self.finished_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "线程数："))
        self.threads_lineEdit.setText(_translate("MainWindow", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dirc_scan_tab1), _translate("MainWindow", "目录扫描"))
        self.web_utl_lineEdit.setText(_translate("MainWindow", "http://192.168.74.135"))
        self.label_12.setText(_translate("MainWindow", "请输入网址:"))
        self.web_start_Button.setText(_translate("MainWindow", "开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Web指纹"))
        self.groupBox_6.setTitle(_translate("MainWindow", "信息"))
        self.label_6.setText(_translate("MainWindow", "IP地址："))
        self.port_ip_lineEdit.setText(_translate("MainWindow", "192.168.74.134"))
        self.port_scan_Button.setText(_translate("MainWindow", "开始扫描"))
        self.port_num_comboBox.setItemText(1, _translate("MainWindow", "TOP50"))
        self.port_num_comboBox.setItemText(2, _translate("MainWindow", "TOP100"))
        self.port_num_comboBox.setItemText(3, _translate("MainWindow", "TOP1000"))
        self.label_8.setText(_translate("MainWindow", "请先选择端口数量："))
        self.groupBox_7.setTitle(_translate("MainWindow", "结果："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "端口扫描"))
        self.label_11.setText(_translate("MainWindow", "域名地址："))
        self.domain_lineEdit.setText(_translate("MainWindow", "baidu.com"))
        self.domain_start_Button.setText(_translate("MainWindow", "开始解析"))
        self.groupBox_8.setTitle(_translate("MainWindow", "A记录"))
        self.groupBox_9.setTitle(_translate("MainWindow", "MX记录"))
        self.groupBox_10.setTitle(_translate("MainWindow", "NS记录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "域名解析"))
        self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">本程序有xxx小组制作。</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "使用帮助"))
        self.label.setText(_translate("MainWindow", "© hannoch"))
        self.menu.setTitle(_translate("MainWindow", "功能菜单"))

    def percent(self, finished, total, per):
        self.finished_lineEdit.setText(str(finished))
        self.all_lineEdit.setText(str(total))
        self.progressBar.setValue(per)



